/* ... existing code ... */
  mathematics: {
    units: [
      'Radian', 'Degree', 'Gradian', 'Turn', 'Pi radian', 'Arcsecond', 'Arcminute', 'Milliradian', 'Microradian',
      'Meter', 'Kilometer', 'Centimeter', 'Millimeter', 'Micrometer', 'Nanometer', 'Ångström', 'Picometer', 'Femtometer',
      'Foot', 'Inch', 'Yard', 'Mile', 'Nautical mile',
      'Square meter', 'Square kilometer', 'Hectare', 'Acre', 'Square foot', 'Square inch', 'Square mile',
      'Cubic meter', 'Liter', 'Milliliter', 'Cubic foot', 'Gallon',
      'Newton', 'Kilonewton', 'Dyne', 'Pound-force', 'Kilogram-force',
      'Pascal', 'Kilopascal', 'Megapascal', 'Bar', 'Atmosphere', 'Pound per square inch', 'Torr', 'Millimeter of mercury',
      'Joule', 'Kilojoule', 'Megajoule', 'Calorie', 'Kilocalorie', 'British thermal unit', 'Foot-pound', 'Electronvolt',
      'Watt', 'Kilowatt', 'Megawatt', 'Horsepower', 'BTU/hour',
      'Hertz', 'Kilohertz', 'Megahertz', 'Gigahertz',
      'Radian per second', 'Revolutions per minute', 'Degrees per second',
      'Meter per second', 'Kilometer per hour', 'Mile per hour', 'Knot',
      'Meter per second squared', 'Standard gravity', 'Gal',
      'Kilogram', 'Gram', 'Milligram', 'Tonne', 'Pound', 'Ounce',
      'Mole', 'Kilomole', 'Millimole', 'Micromole',
      'Kelvin', 'Celsius', 'Fahrenheit', 'Rankine',
      'Pi', 'Euler number', 'Golden ratio', 'Square root of 2', 'Natural logarithm base',
      'Imaginary unit', 'Infinity', 'Summation', 'Product', 'Integral', 'Derivative',
      'Standard deviation', 'Variance', 'Mean', 'Median', 'Mode'
    ],
    baseUnit: 'Radian',
    ratios: {
      'Radian': 1,
      'Degree': 57.2958,
      'Gradian': 63.662,
      'Turn': 0.159155,
      'Pi radian': 0.31831,
      'Arcsecond': 206265,
      'Arcminute': 3437.75,
      'Milliradian': 1000,
      'Microradian': 1000000,
      'Meter': 1,
      'Kilometer': 0.001,
      'Centimeter': 100,
      'Millimeter': 1000,
      'Micrometer': 1000000,
      'Nanometer': 1e+9,
      'Ångström': 1e+10,
      'Picometer': 1e+12,
      'Femtometer': 1e+15,
      'Foot': 3.28084,
      'Inch': 39.3701,
      'Yard': 1.09361,
      'Mile': 0.000621371,
      'Nautical mile': 0.000539957,
      'Square meter': 1,
      'Square kilometer': 1e-6,
      'Hectare': 0.0001,
      'Acre': 0.000247105,
      'Square foot': 10.7639,
      'Square inch': 1550,
      'Square mile': 3.86102e-7,
      'Cubic meter': 1,
      'Liter': 1000,
      'Milliliter': 1e+6,
      'Cubic foot': 35.3147,
      'Gallon': 264.172,
      'Newton': 1,
      'Kilonewton': 0.001,
      'Dyne': 100000,
      'Pound-force': 0.224809,
      'Kilogram-force': 0.101972,
      'Pascal': 1,
      'Kilopascal': 0.001,
      'Megapascal': 1e-6,
      'Bar': 0.00001,
      'Atmosphere': 9.86923e-6,
      'Pound per square inch': 0.000145038,
      'Torr': 0.00750062,
      'Millimeter of mercury': 0.00750062,
      'Joule': 1,
      'Kilojoule': 0.001,
      'Megajoule': 0.000001,
      'Calorie': 0.239006,
      'Kilocalorie': 0.000239006,
      'British thermal unit': 0.000947817,
      'Foot-pound': 0.737562,
      'Electronvolt': 6.242e+18,
      'Watt': 1,
      'Kilowatt': 0.001,
      'Megawatt': 0.000001,
      'Horsepower': 0.00134102,
      'BTU/hour': 3.41214,
      'Hertz': 1,
      'Kilohertz': 0.001,
      'Megahertz': 0.000001,
      'Gigahertz': 1e-9,
      'Radian per second': 1,
      'Revolutions per minute': 9.5493,
      'Degrees per second': 57.2958,
      'Meter per second': 1,
      'Kilometer per hour': 3.6,
      'Mile per hour': 2.23694,
      'Knot': 1.94384,
      'Meter per second squared': 1,
      'Standard gravity': 0.101972,
      'Gal': 100,
      'Kilogram': 1,
      'Gram': 1000,
      'Milligram': 1000000,
      'Tonne': 0.001,
      'Pound': 2.20462,
      'Ounce': 35.274,
      'Mole': 1,
      'Kilomole': 0.001,
      'Millimole': 1000,
      'Micromole': 1000000,
      'Kelvin': 1,
      'Celsius': -272.15,
      'Fahrenheit': -457.87,
      'Rankine': 1.8,
      'Pi': 3.14159,
      'Euler number': 2.71828,
      'Golden ratio': 1.61803,
      'Square root of 2': 1.41421,
      'Natural logarithm base': 2.71828,
      'Imaginary unit': 1,
      'Infinity': 1,
      'Summation': 1,
      'Product': 1,
      'Integral': 1,
      'Derivative': 1,
      'Standard deviation': 1,
      'Variance': 1,
      'Mean': 1,
      'Median': 1,
      'Mode': 1
    }
  },
  medicine: {
    units: ['mg', 'μg', 'g', 'kg', 'lb', 'oz', 'mL', 'L', 'mg/mL', 'μg/mL', 'mg/kg', 'μg/kg', 'BMI', 'kcal', 'mg/day', 'mg/dose', 'mg/tablet', 'mg/capsule', 'mg/5mL', 'mg/mL', 'μg/L', 'mg/L', 'g/dL', 'g/L', 'mIU/L', 'mIU/mL', 'IU/mL', 'U/mL', 'kU/L', 'mmol/L', 'mol/L', 'mmol/kg', 'mmol/kg/day', 'μmol/L', 'nmol/L', 'pmol/L', 'mEq/L', 'mEq', 'mOsmol/L', 'mOsm/kg', 'dL', 'mL/min', 'mL/hr', 'mL/kg/hr', 'L/min', 'drops/min', 'drops/mL', 'ppm', 'ppb', 'mg%', 'IU', 'USP unit', 'mg/day', 'mg BID', 'mg TID', 'mg QD', 'mg once daily', 'mg twice daily', 'mg three times daily', 'mg every 8 hours', 'mg every 12 hours', 'mg per day', 'μg/day', 'μg/d', 'mg/kg', 'mg/kg/day', 'μg/kg/day', 'mg/m²', 'mg/mL', 'μg/mL', 'IU/day', '%', 'mmHg', 'cmH₂O', 'psi', 'atm', 'kPa', '°C', '°F', 'K', 'beats per minute', 'bpm', 'respiratory rate', 'breaths per minute'],
    baseUnit: 'mg',
    ratios: {
      'mg': 1,
      'μg': 1000,
      'g': 0.001,
      'kg': 1e-6,
      'lb': 2.2046e-6,
      'oz': 3.5274e-5,
      'mL': 1,
      'L': 0.001,
      'mg/mL': 1,
      'μg/mL': 1000,
      'mg/kg': 1,
      'μg/kg': 1000,
      'BMI': 1,
      'kcal': 1,
      'mg/day': 1,
      'mg/dose': 1,
      'mg/tablet': 1,
      'mg/capsule': 1,
      'mg/5mL': 1,
      'μg/L': 1000,
      'mg/L': 1,
      'g/dL': 0.01,
      'g/L': 0.001,
      'mIU/L': 1,
      'mIU/mL': 1,
      'IU/mL': 1,
      'U/mL': 1,
      'kU/L': 0.001,
      'mmol/L': 1000,
      'mol/L': 1,
      'mmol/kg': 1,
      'mmol/kg/day': 1,
      'μmol/L': 1000000,
      'nmol/L': 1e+9,
      'pmol/L': 1e+12,
      'mEq/L': 1,
      'mEq': 1,
      'mOsmol/L': 1,
      'mOsm/kg': 1,
      'dL': 10,
      'mL/min': 1,
      'mL/hr': 1,
      'mL/kg/hr': 1,
      'L/min': 0.001,
      'drops/min': 1,
      'drops/mL': 20,
      'ppm': 1000,
      'ppb': 1e+6,
      'mg%': 1,
      'IU': 1,
      'USP unit': 1,
      'mg/day': 1,
      'mg BID': 1,
      'mg TID': 1,
      'mg QD': 1,
      'mg once daily': 1,
      'mg twice daily': 1,
      'mg three times daily': 1,
      'mg every 8 hours': 1,
      'mg every 12 hours': 1,
      'mg per day': 1,
      'μg/day': 1000,
      'μg/d': 1000,
      'mg/kg': 1,
      'mg/kg/day': 1,
      'μg/kg/day': 1000,
      'mg/m²': 1,
      'IU/day': 1,
      '%': 100,
      'mmHg': 1,
      'cmH₂O': 1,
      'psi': 1,
      'atm': 1,
      'kPa': 1,
      '°C': 1,
      '°F': 1,
      'K': 1,
      'beats per minute': 1,
      'bpm': 1,
      'respiratory rate': 1,
      'breaths per minute': 1
    }
  },
  meteorology: {
    units: ['hPa', 'mbar', 'inHg', 'mmHg', 'PSI', 'atm', 'torr', 'Pa', 'kPa', 'MPa', 'bar', 'mmWs', 'inWs', 'inH₂O', 'ftH₂O', 'mH₂O', 'kN/m²', 'lbf/in²', 'lbf/ft²', 'kgf/cm²', 'atmospheric pressure', 'standard atmosphere', 'technical atmosphere', 'celsius', 'fahrenheit', 'kelvin', 'rankine', 'delisle', 'newton', 'réaumur', 'rømer', 'm/s', 'km/h', 'mph', 'knots', 'ft/s', 'm/min', 'ft/min', 'in/s', 'cm/s', 'mm/s', 'percentage', 'relative humidity', 'absolute humidity', 'specific humidity', 'mixing ratio', 'dew point', 'dew point depression', 'wet bulb temperature', 'dry bulb temperature', 'wind chill', 'heat index', 'apparent temperature', 'feels like', 'visibility', 'ceiling', 'cloud cover', 'precipitation', 'rainfall', 'snowfall', 'hail', 'sleet', 'fog', 'mist', 'haze', 'smoke', 'dust', 'sand', 'ash', 'volcanic ash', 'air quality index', 'aqi', 'pm2.5', 'pm10', 'so2', 'no2', 'o3', 'co', 'no', 'no3', 'hno3', 'h2o2', 'hocl', 'hobr', 'h2s', 'nh3', 'ch4', 'co2', 'n2o', 'c2h6', 'c3h8', 'c4h10', 'c5h12', 'c6h14', 'c7h16', 'c8h18', 'c9h20', 'c10h22', 'benzene', 'toluene', 'xylene', 'ethylbenzene', 'styrene', 'isoprene', 'monoterpene', 'sesquiterpene', 'terpene', 'aldehyde', 'ketone', 'alcohol', 'ester', 'ether', 'acid', 'base', 'salt', 'aerosol', 'particulate', 'particle', 'nucleation', 'condensation', 'coagulation', 'deposition', 'dry deposition', 'wet deposition', 'cloud condensation nuclei', 'ccn', 'ice nuclei', 'in', 'aerosol optical depth', 'aod', 'angstrom exponent', 'single scattering albedo', 'asymmetry parameter', 'extinction coefficient', 'scattering coefficient', 'absorption coefficient', 'backscattering coefficient', 'phase function', 'scattering phase function', 'rayleigh scattering', 'mie scattering', 'raman scattering', 'fluorescence', 'phosphorescence', 'chemiluminescence', 'bioluminescence', 'electroluminescence', 'photoluminescence', 'triboluminescence', 'sonoluminescence', 'thermoluminescence', 'radioluminescence', 'cathodoluminescence', 'anodoluminescence', 'ionoluminescence', 'radiation', 'irradiance', 'radiance', 'emittance', 'spectral irradiance', 'spectral radiance', 'spectral emittance', 'wavelength', 'frequency', 'wave number', 'photon', 'photon flux', 'photon density', 'photon energy', 'photon momentum', 'photon spin', 'photon polarization', 'photon helicity', 'photon chirality', 'photon parity', 'photon charge', 'photon mass', 'photon lifetime', 'photon mean free path', 'photon diffusion', 'photon scattering', 'photon absorption', 'photon emission', 'photon creation', 'photon annihilation', 'photon conversion', 'photon interaction', 'photon collision', 'photon pair production', 'photon pair annihilation', 'photon compton scattering', 'photon thomson scattering', 'photon rayleigh scattering', 'photon raman scattering', 'photon brillouin scattering', 'photon mie scattering', 'photon mie theory', 'photon mie solution', 'photon mie coefficient', 'photon mie efficiency', 'photon mie cross section', 'photon mie radius', 'photon mie size parameter', 'photon mie anisotropy', 'photon mie asymmetry', 'photon mie phase function', 'photon mie scattering matrix', 'photon mie stokes vector', 'photon mie polarization', 'photon mie depolarization', 'photon mie circular dichroism', 'photon mie optical activity', 'photon mie chirality', 'photon mie helicity', 'photon mie parity', 'photon mie time reversal', 'photon mie symmetry', 'photon mie conservation laws', 'photon mie energy conservation', 'photon mie momentum conservation', 'photon mie angular momentum conservation', 'photon mie charge conservation', 'photon mie parity conservation', 'photon mie time reversal conservation', 'photon mie cp conservation', 'photon mie cpt conservation', 'photon mie lorentz invariance', 'photon mie gauge invariance', 'photon mie renormalization', 'photon mie regularization', 'photon mie divergences', 'photon mie anomalies', 'photon mie ward identities', 'photon mie slavnov-taylor identities', 'photon mie bianchi identities', 'photon mie jacobi identities', 'photon mie structure constants', 'photon mie coupling constants', 'photon mie fine structure constant', 'photon mie coupling strength', 'photon mie interaction strength', 'photon mie scattering amplitude', 'photon mie scattering cross section', 'photon mie differential cross section', 'photon mie total cross section', 'photon mie absorption cross section', 'photon mie extinction cross section', 'photon mie scattering efficiency', 'photon mie absorption efficiency', 'photon mie extinction efficiency', 'photon mie albedo', 'photon mie single scattering albedo', 'photon mie asymmetry parameter', 'photon mie anisotropy factor', 'photon mie phase function', 'photon mie scattering phase function', 'photon mie henvey-greenstein phase function', 'photon mie rayleigh-gans phase function', 'photon mie isotropic phase function', 'photon mie delta function', 'photon mie dirac delta function', 'photon mie kronecker delta', 'photon mie tensor', 'photon mie vector', 'photon mie scalar', 'photon mie pseudoscalar', 'photon mie axial vector', 'photon mie axial tensor', 'photon mie pseudovector', 'photon mie pseudotensor', 'photon mie dual tensor', 'photon mie hodge dual', 'photon mie levi-civita tensor', 'photon mie permutation tensor', 'photon mie antisymmetric tensor', 'photon mie symmetric tensor', 'photon mie metric tensor', 'photon mie kronecker tensor', 'photon mie identity tensor', 'photon mie null tensor', 'photon mie trace', 'photon mie determinant', 'photon mie eigenvalues', 'photon mie eigenvectors', 'photon mie eigenfunctions', 'photon mie eigenstates', 'photon mie eigenmodes', 'photon mie eigenfrequencies', 'photon mie eigenwavelengths', 'photon mie eigenenergies', 'photon mie eigenmomenta', 'photon mie eigenangular momenta', 'photon mie eigenspins', 'photon mie eigenpolarizations', 'photon mie eigenhelicities', 'photon mie eigenchiralities', 'photon mie eigenparities', 'photon mie eigencharges', 'photon mie eigenmasses', 'photon mie eigenlifetimes', 'photon mie eigenmean free paths', 'photon mie eigenscattering', 'photon mie eigenabsorption', 'photon mie eigenemission', 'photon mie eigeninteraction', 'photon mie eigenprocesses', 'photon mie eigenreactions', 'photon mie eigentransitions'],
    baseUnit: 'Pa',
    ratios: {
      'hPa': 0.01,
      'mbar': 0.01,
      'inHg': 0.000295299,
      'mmHg': 0.00750062,
      'PSI': 0.000145038,
      'atm': 9.86923e-6,
      'torr': 0.00750062,
      'Pa': 1,
      'kPa': 0.001,
      'MPa': 0.000001,
      'bar': 0.00001,
      'mmWs': 0.10197,
      'inWs': 0.03937,
      'inH₂O': 0.00401463,
      'ftH₂O': 0.334553,
      'mH₂O': 0.000101997,
      'kN/m²': 0.001,
      'lbf/in²': 0.000145038,
      'lbf/ft²': 0.0208854,
      'kgf/cm²': 0.0000101972,
      'atmospheric pressure': 1,
      'standard atmosphere': 9.86923e-6,
      'technical atmosphere': 0.00000967841,
      'celsius': 1,
      'fahrenheit': 1,
      'kelvin': 1,
      'rankine': 1,
      'delisle': 1,
      'newton': 1,
      'réaumur': 1,
      'rømer': 1,
      'm/s': 1,
      'km/h': 3.6,
      'mph': 2.23694,
      'knots': 1.94384,
      'ft/s': 3.28084,
      'm/min': 60,
      'ft/min': 196.85,
      'in/s': 39.3701,
      'cm/s': 100,
      'mm/s': 1000,
      'percentage': 100,
      'relative humidity': 100,
      'absolute humidity': 100,
      'specific humidity': 100,
      'mixing ratio': 100,
      'dew point': 1,
      'dew point depression': 1,
      'wet bulb temperature': 1,
      'dry bulb temperature': 1,
      'wind chill': 1,
      'heat index': 1,
      'apparent temperature': 1,
      'feels like': 1,
      'visibility': 1,
      'ceiling': 1,
      'cloud cover': 100,
      'precipitation': 1,
      'rainfall': 1,
      'snowfall': 1,
      'hail': 1,
      'sleet': 1,
      'fog': 1,
      'mist': 1,
      'haze': 1,
      'smoke': 1,
      'dust': 1,
      'sand': 1,
      'ash': 1,
      'volcanic ash': 1,
      'air quality index': 1,
      'aqi': 1,
      'pm2.5': 1,
      'pm10': 1,
      'so2': 1,
      'no2': 1,
      'o3': 1,
      'co': 1,
      'no': 1,
      'no3': 1,
      'hno3': 1,
      'h2o2': 1,
      'hocl': 1,
      'hobr': 1,
      'h2s': 1,
      'nh3': 1,
      'ch4': 1,
      'co2': 1,
      'n2o': 1,
      'c2h6': 1,
      'c3h8': 1,
      'c4h10': 1,
      'c5h12': 1,
      'c6h14': 1,
      'c7h16': 1,
      'c8h18': 1,
      'c9h20': 1,
      'c10h22': 1,
      'benzene': 1,
      'toluene': 1,
      'xylene': 1,
      'ethylbenzene': 1,
      'styrene': 1,
      'isoprene': 1,
      'monoterpene': 1,
      'sesquiterpene': 1,
      'terpene': 1,
      'aldehyde': 1,
      'ketone': 1,
      'alcohol': 1,
      'ester': 1,
      'ether': 1,
      'acid': 1,
      'base': 1,
      'salt': 1,
      'aerosol': 1,
      'particulate': 1,
      'particle': 1,
      'nucleation': 1,
      'condensation': 1,
      'coagulation': 1,
      'deposition': 1,
      'dry deposition': 1,
      'wet deposition': 1,
      'cloud condensation nuclei': 1,
      'ccn': 1,
      'ice nuclei': 1,
      'in': 1,
      'aerosol optical depth': 1,
      'aod': 1,
      'angstrom exponent': 1,
      'single scattering albedo': 1,
      'asymmetry parameter': 1,
      'extinction coefficient': 1,
      'scattering coefficient': 1,
      'absorption coefficient': 1,
      'backscattering coefficient': 1,
      'phase function': 1,
      'scattering phase function': 1,
      'rayleigh scattering': 1,
      'mie scattering': 1,
      'raman scattering': 1,
      'fluorescence': 1,
      'phosphorescence': 1,
      'chemiluminescence': 1,
      'bioluminescence': 1,
      'electroluminescence': 1,
      'photoluminescence': 1,
      'triboluminescence': 1,
      'sonoluminescence': 1,
      'thermoluminescence': 1,
      'radioluminescence': 1,
      'cathodoluminescence': 1,
      'anodoluminescence': 1,
      'ionoluminescence': 1,
      'radiation': 1,
      'irradiance': 1,
      'radiance': 1,
      'emittance': 1,
      'spectral irradiance': 1,
      'spectral radiance': 1,
      'spectral emittance': 1,
      'wavelength': 1,
      'frequency': 1,
      'wave number': 1,
      'photon': 1,
      'photon flux': 1,
      'photon density': 1,
      'photon energy': 1,
      'photon momentum': 1,
      'photon spin': 1,
      'photon polarization': 1,
      'photon helicity': 1,
      'photon chirality': 1,
      'photon parity': 1,
      'photon charge': 1,
      'photon mass': 1,
      'photon lifetime': 1,
      'photon mean free path': 1,
      'photon diffusion': 1,
      'photon scattering': 1,
      'photon absorption': 1,
      'photon emission': 1,
      'photon creation': 1,
      'photon annihilation': 1,
      'photon conversion': 1,
      'photon interaction': 1,
      'photon collision': 1,
      'photon pair production': 1,
      'photon pair annihilation': 1,
      'photon compton scattering': 1,
      'photon thomson scattering': 1,
      'photon rayleigh scattering': 1,
      'photon raman scattering': 1,
      'photon brillouin scattering': 1,
      'photon mie scattering': 1,
      'photon mie theory': 1,
      'photon mie solution': 1,
      'photon mie coefficient': 1,
      'photon mie efficiency': 1,
      'photon mie cross section': 1,
      'photon mie radius': 1,
      'photon mie size parameter': 1,
      'photon mie anisotropy': 1,
      'photon mie asymmetry': 1,
      'photon mie phase function': 1,
      'photon mie scattering matrix': 1,
      'photon mie stokes vector': 1,
      'photon mie polarization': 1,
      'photon mie depolarization': 1,
      'photon mie circular dichroism': 1,
      'photon mie optical activity': 1,
      'photon mie chirality': 1,
      'photon mie helicity': 1,
      'photon mie parity': 1,
      'photon mie time reversal': 1,
      'photon mie symmetry': 1,
      'photon mie conservation laws': 1,
      'photon mie energy conservation': 1,
      'photon mie momentum conservation': 1,
      'photon mie angular momentum conservation': 1,
      'photon mie charge conservation': 1,
      'photon mie parity conservation': 1,
      'photon mie time reversal conservation': 1,
      'photon mie cp conservation': 1,
      'photon mie cpt conservation': 1,
      'photon mie lorentz invariance': 1,
      'photon mie gauge invariance': 1,
      'photon mie renormalization': 1,
      'photon mie regularization': 1,
      'photon mie divergences': 1,
      'photon mie anomalies': 1,
      'photon mie ward identities': 1,
      'photon mie slavnov-taylor identities': 1,
      'photon mie bianchi identities': 1,
      'photon mie jacobi identities': 1,
      'photon mie structure constants': 1,
      'photon mie coupling constants': 1,
      'photon mie fine structure constant': 1,
      'photon mie coupling strength': 1,
      'photon mie interaction strength': 1,
      'photon mie scattering amplitude': 1,
      'photon mie scattering cross section': 1,
      'photon mie differential cross section': 1,
      'photon mie total cross section': 1,
      'photon mie absorption cross section': 1,
      'photon mie extinction cross section': 1,
      'photon mie scattering efficiency': 1,
      'photon mie absorption efficiency': 1,
      'photon mie extinction efficiency': 1,
      'photon mie albedo': 1,
      'photon mie single scattering albedo': 1,
      'photon mie asymmetry parameter': 1,
      'photon mie anisotropy factor': 1,
      'photon mie phase function': 1,
      'photon mie scattering phase function': 1,
      'photon mie henvey-greenstein phase function': 1,
      'photon mie rayleigh-gans phase function': 1,
      'photon mie isotropic phase function': 1,
      'photon mie delta function': 1,
      'photon mie dirac delta function': 1,
      'photon mie kronecker delta': 1,
      'photon mie tensor': 1,
      'photon mie vector': 1,
      'photon mie scalar': 1,
      'photon mie pseudoscalar': 1,
      'photon mie axial vector': 1,
      'photon mie axial tensor': 1,
      'photon mie pseudovector': 1,
      'photon mie pseudotensor': 1,
      'photon mie dual tensor': 1,
      'photon mie hodge dual': 1,
      'photon mie levi-civita tensor': 1,
      'photon mie permutation tensor': 1,
      'photon mie antisymmetric tensor': 1,
      'photon mie symmetric tensor': 1,
      'photon mie metric tensor': 1,
      'photon mie kronecker tensor': 1,
      'photon mie identity tensor': 1,
      'photon mie null tensor': 1,
      'photon mie trace': 1,
      'photon mie determinant': 1,
      'photon mie eigenvalues': 1,
      'photon mie eigenvectors': 1,
      'photon mie eigenfunctions': 1,
      'photon mie eigenstates': 1,
      'photon mie eigenmodes': 1,
      'photon mie eigenfrequencies': 1,
      'photon mie eigenwavelengths': 1,
      'photon mie eigenenergies': 1,
      'photon mie eigenmomenta': 1,
      'photon mie eigenangular momenta': 1,
      'photon mie eigenspins': 1,
      'photon mie eigenpolarizations': 1,
      'photon mie eigenhelicities': 1,
      'photon mie eigenchiralities': 1,
      'photon mie eigenparities': 1,
      'photon mie eigencharges': 1,
      'photon mie eigenmasses': 1,
      'photon mie eigenlifetimes': 1,
      'photon mie eigenmean free paths': 1,
      'photon mie eigenscattering': 1,
      'photon mie eigenabsorption': 1,
      'photon mie eigenemission': 1,
      'photon mie eigeninteraction': 1,
      'photon mie eigenprocesses': 1,
      'photon mie eigenreactions': 1,
      'photon mie eigentransitions': 1
    }
  },
  optics: {
    units: ['lux', 'lumens', 'candela', 'foot-candle', 'phot', 'milliphot', 'nit', 'stilb', 'apostilb', 'lambert', 'foot-lambert', 'bril', 'skot', 'candela/m²', 'candela/ft²', 'candela/in²', 'lumen/m²', 'lumen/ft²', 'lumen/in²', 'watt/steradian', 'watt/m²', 'watt/cm²', 'watt/m²/sr', 'watt/cm²/sr', 'luminous efficacy', 'luminous intensity', 'illuminance', 'luminance', 'luminous flux'],
    baseUnit: 'lux',
    ratios: {
      'lux': 1,
      'lumens': 1,
      'candela': 1,
      'foot-candle': 0.092903,
      'phot': 0.0001,
      'milliphot': 0.1,
      'nit': 0.001,
      'stilb': 0.0001,
      'apostilb': 0.31831,
      'lambert': 3.1831e-5,
      'foot-lambert': 0.291863,
      'bril': 1000,
      'skot': 1000,
      'candela/m²': 0.001,
      'candela/ft²': 0.0092903,
      'candela/in²': 0.00064516,
      'lumen/m²': 1,
      'lumen/ft²': 0.092903,
      'lumen/in²': 0.00064516,
      'watt/steradian': 683.002,
      'watt/m²': 683.002,
      'watt/cm²': 6.83002,
      'watt/m²/sr': 683.002,
      'watt/cm²/sr': 6.83002,
      'luminous efficacy': 1,
      'luminous intensity': 1,
      'illuminance': 1,
      'luminance': 1,
      'luminous flux': 1
    }
  },
  nuclear: {
    units: [
      'Becquerel', 'Curie', 'Rutherford', 'Gray', 'Rad', 'Sievert', 'Rem',
      'Electron Volt', 'Giga-electron Volt', 'Tera-electron Volt', 'Mega-electron Volt',
      'Kilo-electron Volt', 'Joule', 'Kilojoule', 'Megajoule', 'Gigajoule', 'Watt', 'Kilowatt',
      'Megawatt', 'Gigawatt', 'Erg', 'Calorie', 'Kilocalorie', 'British Thermal Unit',
      'Foot-pound', 'Ton of TNT', 'Therm', 'Kilogram', 'Gram', 'Milligram', 'Microgram',
      'Nanogram', 'Pound', 'Ounce', 'Tonne', 'Long Ton', 'Short Ton', 'Atomic Mass Unit',
      'Dalton', 'MeV/Fm', 'QJ/Fm', 'Picometer', 'Femtometer', 'Atom', 'Particle', 'Barn',
      'Millibarn', 'Microbarn', 'Nanobarn', 'Picobarn', 'Femtobarn', 'Attobarn', 'Zeptobarn',
      'Yoctobarn', 'Neutron Flux', 'Gamma Ray', 'Alpha Particle', 'Beta Particle', 'Neutron',
      'Proton', 'Deuteron', 'Triton', 'Helion', 'Fission', 'Fusion', 'Half-life', 'Decay Rate',
      'Activity', 'Dose Rate', 'Exposure Rate', 'Flux Density', 'Energy Fluence', 'Particle Fluence',
      'Linear Attenuation Coefficient', 'Mass Attenuation Coefficient', 'Cross Section',
      'Mean Free Path', 'Relaxation Length', 'Buildup Factor', 'Dose Coefficient',
      'Effective Dose', 'Committed Dose', 'Annual Limit', 'Derived Air Concentration',
      'Maximum Permissible Concentration', 'Quality Factor', 'Relative Biological Effectiveness',
      'Linear Energy Transfer', 'Stopping Power', 'Range', 'Straggling', 'Bremsstrahlung',
      'Cerenkov Radiation', 'Synchrotron Radiation', 'Compton Scattering', 'Photoelectric Effect',
      'Pair Production', 'Annihilation', 'Nuclear Reaction', 'Chain Reaction', 'Critical Mass',
      'Multiplication Factor', 'Reactivity', 'Delayed Neutrons', 'Prompt Neutrons', 'Thermal Neutrons',
      'Fast Neutrons', 'Epithermal Neutrons', 'Resonance Neutrons', 'Moderator', 'Reflector',
      'Control Rod', 'Fuel Rod', 'Coolant', 'Shielding', 'Containment', 'Reactor Core',
      'Nuclear Fuel', 'Enriched Uranium', 'Depleted Uranium', 'Plutonium', 'Thorium', 'Tritium',
      'Deuterium', 'Heavy Water', 'Graphite', 'Beryllium', 'Lead', 'Concrete', 'Steel', 'Aluminum',
      'Cadmium', 'Boron', 'Hafnium', 'Silver', 'Indium', 'Gadolinium', 'Samarium', 'Europium',
      'Californium', 'Americium', 'Curium', 'Berkelium', 'Einsteinium', 'Fermium', 'Mendelevium',
      'Nobelium', 'Lawrencium', 'Rutherfordium', 'Dubnium', 'Seaborgium', 'Bohrium', 'Hassium',
      'Meitnerium', 'Darmstadtium', 'Roentgenium', 'Copernicium', 'Nihonium', 'Flerovium',
      'Moscovium', 'Livermorium', 'Tennessine', 'Oganesson'
    ],
    baseUnit: 'Becquerel',
    ratios: {
      'Becquerel': 1,
      'Curie': 2.7027e-11,
      'Rutherford': 0.000001,
      'Gray': 1,
      'Rad': 100,
      'Sievert': 1,
      'Rem': 100,
      'Electron Volt': 6.242e+18,
      'Giga-electron Volt': 6.242e+9,
      'Tera-electron Volt': 6.242e+6,
      'Mega-electron Volt': 6.242e+12,
      'Kilo-electron Volt': 6.242e+15,
      'Joule': 1,
      'Kilojoule': 0.001,
      'Megajoule': 0.000001,
      'Gigajoule': 1e-9,
      'Watt': 1,
      'Kilowatt': 0.001,
      'Megawatt': 0.000001,
      'Gigawatt': 1e-9,
      'Erg': 10000000,
      'Calorie': 0.239006,
      'Kilocalorie': 0.000239006,
      'British Thermal Unit': 0.000947817,
      'Foot-pound': 0.737562,
      'Ton of TNT': 2.39006e-10,
      'Therm': 9.48043e-9,
      'Kilogram': 1,
      'Gram': 1000,
      'Milligram': 1000000,
      'Microgram': 1e+9,
      'Nanogram': 1e+12,
      'Pound': 2.20462,
      'Ounce': 35.274,
      'Tonne': 0.001,
      'Long Ton': 0.000984207,
      'Short Ton': 0.00110231,
      'Atomic Mass Unit': 6.022e+26,
      'Dalton': 6.022e+26,
      'MeV/Fm': 6.242e+18,
      'QJ/Fm': 1,
      'Picometer': 0.000000001,
      'Femtometer': 1e-15,
      'Atom': 1,
      'Particle': 1,
      'Barn': 1e+28,
      'Millibarn': 1e+25,
      'Microbarn': 1e+22,
      'Nanobarn': 1e+19,
      'Picobarn': 1e+16,
      'Femtobarn': 1e+13,
      'Attobarn': 1e+10,
      'Zeptobarn': 1e+7,
      'Yoctobarn': 10000,
      'Neutron Flux': 1,
      'Gamma Ray': 1,
      'Alpha Particle': 1,
      'Beta Particle': 1,
      'Neutron': 1,
      'Proton': 1,
      'Deuteron': 1,
      'Triton': 1,
      'Helion': 1,
      'Fission': 1,
      'Fusion': 1,
      'Half-life': 1,
      'Decay Rate': 1,
      'Activity': 1,
      'Dose Rate': 1,
      'Exposure Rate': 1,
      'Flux Density': 1,
      'Energy Fluence': 1,
      'Particle Fluence': 1,
      'Linear Attenuation Coefficient': 1,
      'Mass Attenuation Coefficient': 1,
      'Cross Section': 1,
      'Mean Free Path': 1,
      'Relaxation Length': 1,
      'Buildup Factor': 1,
      'Dose Coefficient': 1,
      'Effective Dose': 1,
      'Committed Dose': 1,
      'Annual Limit': 1,
      'Derived Air Concentration': 1,
      'Maximum Permissible Concentration': 1,
      'Quality Factor': 1,
      'Relative Biological Effectiveness': 1,
      'Linear Energy Transfer': 1,
      'Stopping Power': 1,
      'Range': 1,
      'Straggling': 1,
      'Bremsstrahlung': 1,
      'Cerenkov Radiation': 1,
      'Synchrotron Radiation': 1,
      'Compton Scattering': 1,
      'Photoelectric Effect': 1,
      'Pair Production': 1,
      'Annihilation': 1,
      'Nuclear Reaction': 1,
      'Chain Reaction': 1,
      'Critical Mass': 1,
      'Multiplication Factor': 1,
      'Reactivity': 1,
      'Delayed Neutrons': 1,
      'Prompt Neutrons': 1,
      'Thermal Neutrons': 1,
      'Fast Neutrons': 1,
      'Epithermal Neutrons': 1,
      'Resonance Neutrons': 1,
      'Moderator': 1,
      'Reflector': 1,
      'Control Rod': 1,
      'Fuel Rod': 1,
      'Coolant': 1,
      'Shielding': 1,
      'Containment': 1,
      'Reactor Core': 1,
      'Nuclear Fuel': 1,
      'Enriched Uranium': 1,
      'Depleted Uranium': 1,
      'Plutonium': 1,
      'Thorium': 1,
      'Tritium': 1,
      'Deuterium': 1,
      'Heavy Water': 1,
      'Graphite': 1,
      'Beryllium': 1,
      'Lead': 1,
      'Concrete': 1,
      'Steel': 1,
      'Aluminum': 1,
      'Cadmium': 1,
      'Boron': 1,
      'Hafnium': 1,
      'Silver': 1,
      'Indium': 1,
      'Gadolinium': 1,
      'Samarium': 1,
      'Europium': 1,
      'Californium': 1,
      'Americium': 1,
      'Curium': 1,
      'Berkelium': 1,
      'Einsteinium': 1,
      'Fermium': 1,
      'Mendelevium': 1,
      'Nobelium': 1,
      'Lawrencium': 1,
      'Rutherfordium': 1,
      'Dubnium': 1,
      'Seaborgium': 1,
      'Bohrium': 1,
      'Hassium': 1,
      'Meitnerium': 1,
      'Darmstadtium': 1,
      'Roentgenium': 1,
      'Copernicium': 1,
      'Nihonium': 1,
      'Flerovium': 1,
      'Moscovium': 1,
      'Livermorium': 1,
      'Tennessine': 1,
      'Oganesson': 1
    }
  },
  chemistry: {
    units: ['mole', 'kilomole', 'millimole', 'micromole', 'nanomole', 'picomole', 'gram', 'kilogram', 'milligram', 'microgram', 'nanogram', 'pound', 'ounce', 'ton', 'ppm', 'ppb', 'ppt', 'percent', 'molarity', 'molality', 'normality', 'equivalent', 'osmole', 'osmolality', 'osmolarity', 'gEq/L', 'gEq/Kg', 'mgEq/L', 'mgEq/Kg', 'μgEq/L', 'μgEq/Kg', 'pgEq/L', 'pgEq/Kg', 'equivalent weight', 'molecular weight', 'formula weight', 'atomic weight', 'isotopic mass', 'mass number', 'neutron number', 'proton number', 'atomic number', 'Valence', 'Oxidation state', 'Electronic configuration', 'molecules', 'atoms', 'particles', 'ions', 'electrons', 'protons', 'neutrons', 'molal', 'molar', 'g mol/L', 'g mol/kg', 'kg mol/L', 'kg mol/kg', 'mM', 'μM', 'nM', 'pM', 'fM', 'aM', 'pH', 'pOH', 'pKa', 'pKb', 'redox potential', 'stability constant', 'dissociation constant', 'equilibrium constant', 'rate constant', 'activation energy', 'enthalpy', 'entropy', 'free energy', 'heat capacity', 'specific heat', 'heat of formation', 'heat of combustion', 'heat of vaporization', 'heat of fusion', 'latent heat', 'calorific value', 'energy density', 'power density'],
    baseUnit: 'mole',
    ratios: {
      'mole': 1,
      'kilomole': 0.001,
      'millimole': 1000,
      'micromole': 1000000,
      'nanomole': 1e+9,
      'picomole': 1e+12,
      'gram': 1,
      'kilogram': 0.001,
      'milligram': 1000,
      'microgram': 1e+6,
      'nanogram': 1e+9,
      'pound': 0.00220462,
      'ounce': 0.035274,
      'ton': 1e-6,
      'ppm': 1000000,
      'ppb': 1e+9,
      'ppt': 1e+12,
      'percent': 100,
      'molarity': 1,
      'molality': 1,
      'normality': 1,
      'equivalent': 1,
      'osmole': 1,
      'osmolality': 1,
      'osmolarity': 1,
      'gEq/L': 1,
      'gEq/Kg': 1,
      'mgEq/L': 1000,
      'mgEq/Kg': 1000,
      'μgEq/L': 1e+6,
      'μgEq/Kg': 1e+6,
      'pgEq/L': 1e+9,
      'pgEq/Kg': 1e+9,
      'equivalent weight': 1,
      'molecular weight': 1,
      'formula weight': 1,
      'atomic weight': 1,
      'isotopic mass': 1,
      'mass number': 1,
      'neutron number': 1,
      'proton number': 1,
      'atomic number': 1,
      'Valence': 1,
      'Oxidation state': 1,
      'Electronic configuration': 1,
      'molecules': 6.022e+23,
      'atoms': 6.022e+23,
      'particles': 6.022e+23,
      'ions': 6.022e+23,
      'electrons': 6.022e+23,
      'protons': 6.022e+23,
      'neutrons': 6.022e+23,
      'molal': 1,
      'molar': 1,
      'g mol/L': 1,
      'g mol/kg': 1,
      'kg mol/L': 0.001,
      'kg mol/kg': 0.001,
      'mM': 1000,
      'μM': 1000000,
      'nM': 1e+9,
      'pM': 1e+12,
      'fM': 1e+15,
      'aM': 1e+18,
      'pH': 1,
      'pOH': 1,
      'pKa': 1,
      'pKb': 1,
      'redox potential': 1,
      'stability constant': 1,
      'dissociation constant': 1,
      'equilibrium constant': 1,
      'rate constant': 1,
      'activation energy': 1,
      'enthalpy': 1,
      'entropy': 1,
      'free energy': 1,
      'heat capacity': 1,
      'specific heat': 1,
      'heat of formation': 1,
      'heat of combustion': 1,
      'heat of vaporization': 1,
      'heat of fusion': 1,
      'latent heat': 1,
      'calorific value': 1,
      'energy density': 1,
      'power density': 1
    }
  },
  pharmacy: {
    units: ['mg', 'mcg (μg)', 'ng', 'pg', 'fg', 'kg', 'g', 'dg', 'cg', 'mg', 'µg', 'lb', 'oz', 'dr', 'gr', 'scruple', 'dram', 'teaspoon', 'tablespoon', 'fluid ounce', 'cup', 'pint', 'quart', 'gallon', 'milliliter', 'liter', 'kiloliter', 'cup', 'pint', 'quart', 'gallon', 'fluid ounce', 'teaspoon', 'tablespoon', 'drop', 'minim', 'fluid dram', 'tablespoon', 'teaspoon', 'milligram', 'microgram', 'nanogram', 'picogram', 'femtogram', 'attogram', 'international unit', 'unit', 'ampule', 'vial', 'bottle', 'capsule', 'tablet', 'suppository', 'ointment', 'cream', 'gel', 'lotion', 'suspension', 'emulsion', 'solution', 'infusion', 'injection', 'intravenous', 'intramuscular', 'subcutaneous', 'oral', 'topical', 'inhaled', 'suppository', 'transdermal', 'patch', 'sublingual', 'buccal', 'intranasal', 'ophthalmic', 'otic', 'rectal', 'vaginal', 'urethral', 'catheter', 'infusion pump', 'syringe', 'needle', 'gauge', 'milliliter per hour', 'drops per minute', 'mg per kg', 'mcg per kg', 'mg per m²', 'mcg per m²', 'IU', 'USP unit', 'IU/L', 'USP unit/L', 'USP', 'BP', 'EP', 'JP', 'mg/mL', 'mcg/mL', 'ng/mL', 'pg/mL', 'mg/L', 'μg/L', 'ng/L', 'pg/L'],
    baseUnit: 'mg',
    ratios: {
      'mg': 1,
      'mcg (μg)': 1000,
      'ng': 1000000,
      'pg': 1e+9,
      'fg': 1e+12,
      'kg': 0.001,
      'g': 0.001,
      'dg': 0.01,
      'cg': 0.1,
      'mg': 1,
      'µg': 1000,
      'lb': 0.00000220462,
      'oz': 0.000035274,
      'dr': 0.000257206,
      'gr': 0.0154324,
      'scruple': 0.000771618,
      'dram': 0.000257206,
      'teaspoon': 0.0002,
      'tablespoon': 0.0000666667,
      'fluid ounce': 0.000033814,
      'cup': 0.00416667,
      'pint': 0.00211338,
      'quart': 0.00105669,
      'gallon': 0.000264172,
      'milliliter': 0.001,
      'liter': 0.000001,
      'kiloliter': 1e-9,
      'drop': 0.05,
      'minim': 0.0162307,
      'fluid dram': 0.000270512,
      'tablespoon': 0.0000666667,
      'teaspoon': 0.0002,
      'milligram': 1,
      'microgram': 1000,
      'nanogram': 1000000,
      'picogram': 1e+9,
      'femtogram': 1e+12,
      'attogram': 1e+15,
      'international unit': 1,
      'unit': 1,
      'ampule': 1,
      'vial': 1,
      'bottle': 1,
      'capsule': 1,
      'tablet': 1,
      'suppository': 1,
      'ointment': 1,
      'cream': 1,
      'gel': 1,
      'lotion': 1,
      'suspension': 1,
      'emulsion': 1,
      'solution': 1,
      'infusion': 1,
      'injection': 1,
      'intravenous': 1,
      'intramuscular': 1,
      'subcutaneous': 1,
      'oral': 1,
      'topical': 1,
      'inhaled': 1,
      'transdermal': 1,
      'patch': 1,
      'sublingual': 1,
      'buccal': 1,
      'intranasal': 1,
      'ophthalmic': 1,
      'otic': 1,
      'rectal': 1,
      'vaginal': 1,
      'urethral': 1,
      'catheter': 1,
      'infusion pump': 1,
      'syringe': 1,
      'needle': 1,
      'gauge': 1,
      'milliliter per hour': 0.001,
      'drops per minute': 0.00333333,
      'mg per kg': 1,
      'mcg per kg': 1000,
      'mg per m²': 1,
      'mcg per m²': 1000,
      'IU': 1,
      'USP unit': 1,
      'IU/L': 1,
      'USP unit/L': 1,
      'USP': 1,
      'BP': 1,
      'EP': 1,
      'JP': 1,
      'mg/mL': 1,
      'mcg/mL': 1000,
      'ng/mL': 1000000,
      'pg/mL': 1e+9,
      'mg/L': 1,
      'μg/L': 1000,
      'ng/L': 1000000,
      'pg/L': 1e+9
    }
  },
  nutrition: {
    units: ['calorie', 'kilocalorie', 'joule', 'kilojoule', 'megajoule', 'foot-pound', 'inch-pound', 'BTU', 'erg', 'therm', 'ton of tnt', 'watt-hour', 'kilowatt-hour', 'megawatt-hour', 'horsepower-hour', 'electron-volt', 'food calorie', 'dietary calorie', 'metabolic calorie', 'thermochemical calorie', 'international calorie', 'gram', 'kilogram', 'milligram', 'microgram', 'nanogram', 'pound', 'ounce', 'dram', 'grain', 'scruple', 'carat', 'ounce-troy', 'pound-troy', 'ton', 'short ton', 'long ton', 'metric ton', 'percentage', 'grams per serving', 'grams per 100g', 'milligrams per serving', 'micrograms per serving', 'international unit', 'IU', 'USP unit', 'RDA', 'RDI', 'DV', 'AI', 'UL', 'EAR', 'g/day', 'mg/day', 'μg/day', 'IU/day', 'kcal/day', 'kcal/100g', 'kcal/serving', 'g protein', 'g fat', 'g carbohydrate', 'g fiber', 'g sugar', 'mg sodium', 'mg cholesterol', 'g saturated fat', 'g monounsaturated fat', 'g polyunsaturated fat', 'g trans fat', 'mg cholesterol', 'g dietary fiber', 'g soluble fiber', 'g insoluble fiber', 'g sugar alcohols', 'g starch', 'g added sugars', 'g protein', 'g amino acids', 'g vitamins', 'mg minerals', 'μg trace minerals', 'IU vitamins', 'mg sodium', 'mg potassium', 'mg calcium', 'mg iron', 'mg magnesium', 'mg zinc', 'mg copper', 'mg phosphorus', 'mg manganese', 'mg selenium', 'μg iodine', 'μg chromium', 'μg molybdenum', 'mg fluoride', 'μg cobalt', 'mg nickel', 'mg silicon', 'mg boron', 'mg vanadium', 'μg lithium', 'μg strontium', 'Vitamin A IU', 'Vitamin D IU', 'Vitamin E IU', 'Vitamin K μg', 'Vitamin C mg', 'Thiamin mg', 'Riboflavin mg', 'Niacin mg', 'Vitamin B6 mg', 'Folate μg', 'Vitamin B12 μg', 'Biotin μg', 'Pantothenic acid mg', 'Choline mg', 'Calcium mg', 'Iron mg', 'Magnesium mg', 'Phosphorus mg', 'Potassium mg', 'Sodium mg', 'Zinc mg', 'Copper mg', 'Manganese mg', 'Selenium μg', 'Chromium μg', 'Molybdenum μg', 'Chloride mg', 'Protein g', 'Total fat g', 'Saturated fat g', 'Trans fat g', 'Polyunsaturated fat g', 'Monounsaturated fat g', 'Cholesterol mg', 'Total carbohydrate g', 'Dietary fiber g', 'Total sugars g', 'Added sugars g', 'Calcium % DV', 'Iron % DV', 'Vitamin D % DV', 'Potassium % DV'],
    baseUnit: 'calorie',
    ratios: {
      'calorie': 1,
      'kilocalorie': 0.001,
      'joule': 4.184,
      'kilojoule': 0.004184,
      'megajoule': 0.000004184,
      'foot-pound': 3.08596,
      'inch-pound': 37.0315,
      'BTU': 0.00396567,
      'erg': 4.184e+7,
      'therm': 3.96567e-8,
      'ton of tnt': 1e-9,
      'watt-hour': 0.00116222,
      'kilowatt-hour': 0.00000116222,
      'megawatt-hour': 1.16222e-9,
      'horsepower-hour': 0.00000158018,
      'electron-volt': 2.611e+19,
      'food calorie': 1,
      'dietary calorie': 1,
      'metabolic calorie': 1,
      'thermochemical calorie': 1,
      'international calorie': 1,
      'gram': 0.239006,
      'kilogram': 0.000239006,
      'milligram': 239.006,
      'microgram': 239006,
      'nanogram': 239006000,
      'pound': 0.000526911,
      'ounce': 0.00843058,
      'dram': 0.134889,
      'grain': 3.68549,
      'scruple': 0.184275,
      'carat': 1.19503,
      'ounce-troy': 0.00768008,
      'pound-troy': 0.000640007,
      'ton': 0.000000526911,
      'short ton': 0.000000526911,
      'long ton': 0.000000479306,
      'metric ton': 0.000239006,
      'percentage': 100,
      'grams per serving': 1,
      'grams per 100g': 1,
      'milligrams per serving': 1000,
      'micrograms per serving': 1000000,
      'international unit': 1,
      'IU': 1,
      'USP unit': 1,
      'RDA': 1,
      'RDI': 1,
      'DV': 1,
      'AI': 1,
      'UL': 1,
      'EAR': 1,
      'g/day': 1,
      'mg/day': 1000,
      'μg/day': 1000000,
      'IU/day': 1,
      'kcal/day': 0.001,
      'kcal/100g': 0.001,
      'kcal/serving': 0.001,
      'g protein': 1,
      'g fat': 1,
      'g carbohydrate': 1,
      'g fiber': 1,
      'g sugar': 1,
      'mg sodium': 1000,
      'mg cholesterol': 1000
    }
  }
});

// Add smooth scrolling and enhanced interactions
document.querySelectorAll('.tab').forEach(tab => {
  tab.addEventListener('click', (e) => {
    // Add click animation
    e.target.style.transform = 'translateY(0) scale(0.95)';
    setTimeout(() => {
      e.target.style.transform = '';
    }, 150);
    
    // Smooth transition for content
    const converterSection = document.querySelector('.converter-section');
    converterSection.style.opacity = '0.7';
    setTimeout(() => {
      converterSection.style.opacity = '1';
    }, 200);
  });
});

// Add stagger animation for tabs on load
window.addEventListener('load', () => {
  const tabs = document.querySelectorAll('.tab');
  tabs.forEach((tab, index) => {
    tab.style.opacity = '0';
    tab.style.transform = 'translateY(20px)';
    setTimeout(() => {
      tab.style.transition = 'all 0.6s cubic-bezier(0.4, 0, 0.2, 1)';
      tab.style.opacity = '1';
      tab.style.transform = 'translateY(0)';
    }, index * 50);
  });
});

// Add hover sound effect (optional)
let isHovering = false;
document.querySelectorAll('.tab').forEach(tab => {
  tab.addEventListener('mouseenter', () => {
    if (!isHovering) {
      isHovering = true;
      tab.style.transition = 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
    }
  });
  
  tab.addEventListener('mouseleave', () => {
    isHovering = false;
    tab.style.transition = 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)';
  });
});